name: Discussions Announcement Post Handler

on:
  discussion:
    types: created

jobs:
  publish-announcement:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        if: ${{ github.event.discussion && !github.event.comment && github.event.discussion.category.name == 'announcements' }}
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.ANNOUNCEMENTS_WEBHOOK_URL }}
          content: "<@&1092153045942550558> New Minecraft Asset Extractor announcement! ${{ github.event.discussion.html_url }}"